# Generated by Django 5.2.14 on 2026-06-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkoutSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('exercise', models.CharField(choices=[('squat', '스쿼트'), ('lunge', '런지'), ('plank', '플랭크'), ('overhead_press', '오버헤드 프레스')], max_length=50)),
                ('set_number', models.IntegerField()),
                ('score', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
