# Generated by Django 5.2.14 on 2026-06-02 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='workoutsession',
            name='rep_scores',
            field=models.JSONField(default=list),
        ),
    ]
