# Generated by Django 5.2.14 on 2026-06-02 18:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_workoutsession_rep_scores'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepClip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=100)),
                ('exercise', models.CharField(choices=[('squat', '스쿼트'), ('lunge', '런지'), ('plank', '플랭크'), ('overhead_press', '오버헤드 프레스')], max_length=50)),
                ('rep_number', models.IntegerField()),
                ('score', models.FloatField()),
                ('video_file', models.FileField(upload_to='rep_clips/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='clips', to='workout.workoutsession')),
            ],
        ),
    ]
